### ISSUE TITLE
SSl error on first run

### ISSUE THREAD

**Issue by TimN0001** [Baviaan/lotro#15]
C:\lotrobot-6.6.0\source>python main.py
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000015110C745E0>
Traceback (most recent call last):
  File "C:\Users\timne\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 321, in __del__
    self.close()
  File "C:\Users\timne\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 316, in close
    self._ssl_protocol._start_shutdown()
  File "C:\Users\timne\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 599, in _start_shutdown
    self._write_appdata(b'')
  File "C:\Users\timne\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 604, in _write_appdata
    self._process_write_backlog()
  File "C:\Users\timne\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 712, in _process_write_backlog
    self._fatal_error(exc, 'Fatal error on SSL transport')
  File "C:\Users\timne\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 726, in _fatal_error
    self._transport._force_close(exc)
  File "C:\Users\timne\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 151, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "C:\Users\timne\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\timne\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

C:\lotrobot-6.6.0\source>

**Comment by TimN0001** [comment]
I resolved this issue by looking in the raid-bot.log and saw "ERROR: The bot is not in any guilds. Shutting down." so I went back and added the kinship to the bot.
